
server:
  port: 8888
spring:
  application:
    name: bcp-bootcamp-configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/bryanap3294/BOOTCAMP-INTEGRADOR-REPOCONFIG.git
          default-label: main
          timeout: 10
